### ISSUE TITLE
"open" is typically mapped to "openvt" on Linux systems

### ISSUE THREAD

**Issue by rslindee** [romainl/vim-devdocs#1]
On my Fedora system (and presumably other Linux distros) the "open" command is mapped to "openvt". Per my understanding, openvt serves an entirely different purpose than the Mac OS "open" or Linux "xdg-open".

A simple solution might be to check for xdg-open first (I assume this isn't used on Mac OS) or make the desired "open command" configurable via variable.

**Comment by romainl** [comment]
Good suggestions. I'll see if I can do it this week-end.

(Or you could send a PR ;-))

**Comment by romainl** [comment]
@rslindee Could you try that commit I just pushed?

You can customize your command with:

    let g:devdocs_open_command = "open"

**Comment by rslindee** [comment]
Thanks a million for the quick turnaround. That commit indeed works great.
