### ISSUE TITLE
Neovim Doesn't Update Screen Until after Opened DevDocs Window is Closed

### ISSUE THREAD

**Issue by Mootikins** [romainl/vim-devdocs#4]
As the title says, the plugin (for me) doesn't let me see what I am doing in the file until I have closed the DevDocs window/tab. The actions still register, just don't display. Neovim version is 0.3.4, plugin is up to date with master branch.

**Comment by romainl** [comment]
Hello @Mootikins. This plugin is a Vim plugin so a) there is no guarantee whatsoever that it works in other programs and b) I only provide support for Vim.
