### ISSUE TITLE
Windows broken

### ISSUE THREAD

**Issue by Xatenev** [romainl/vim-devdocs#5]
Hi,

the plugin is broken on windows 10 because I think the `explorer` utility is used wrongly. It tries to open a folder in the explorer instead of opening it as URL.

I tracked the problem down to the usage of single quotes. Example (in `cmd`):

```
explorer 'https://devdocs.io/#q=123' // doesn't work
explorer "https://devdocs.io/#q=123" // does work
```

I am not good with vimscript, I tried to change the gist snippet (because it has less code and looked easier to use, the problems persists in the plugin AND in the gist) to : 

```
" What command to use
function! Cmd() abort
    if executable("xdg-open")
        return "xdg-open"
    endif
    if executable("open")
        return "open"
    endif
    return "explorer"
endfunction

" Build the URL stub
let s:stub = Cmd() . " \"https://devdocs.io/#q="

" Build the command
command! -bang -nargs=* DD silent! call system(len(split(<q-args>, ' ')) == 0 ?
            \ s:stub . (expand('<bang>') == "!" || &filetype . '%20') . expand('<cword>') . "\"" : len(split(<q-args>, ' ')) == 1 ?
            \ s:stub . (expand('<bang>') == "!" || &filetype . '%20') . <q-args> . "\"" : s:stub . substitute(<q-args>, '\s\+', '%20', 'g') . "\"")

set keywordprg=:DD
```

this works **almost** . It opens https://devdocs.io/#q=0keyword (note the leading 0). Not sure where the 0 is comming from :)

Greetings
Xatenev

**Comment by romainl** [comment]
Could you add this command to `devdocs.vim` and tell me what's the output?

    command! -bang -nargs=* DDebug echo <SID>DD(<q-args>, expand("<bang>"))

In a `foo.js` file with `for` as its only content, doing `:DDdebug` with the cursor on `for` should echo this:

    explorer "https://devdocs.io/#q=javascript%20for"

Also, I've tested it in the latest official Vim build for Windows, on Windows 10 Professional, in GVim:

![dd](https://user-images.githubusercontent.com/344335/68024443-6de6e880-fcaa-11e9-9581-004611c1db42.gif)

and in Vim:

![dd2](https://user-images.githubusercontent.com/344335/68024444-6de6e880-fcaa-11e9-8110-53bce11556d8.gif)

**Comment by Xatenev** [comment]
Sorry, it seems to work now, not sure what has changed or even if something has changed. Thx for the fast help though. I close this issue
